# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "lms" do |lms|
    lms.vm.box = "ubuntu/trusty64"

    lms.vm.provision "file", source: "upstart", destination: "~/verify-local-matching-service-example.conf"
    lms.vm.provision "file", source: "lms.env", destination: "~/lms.env"

    lms.vm.provision "shell", path: "provision.sh"
  end
end
