server:
  applicationConnectors:
    - type: http
      port: ${MSA_PORT:-50210}
  adminConnectors:
    - type: http
      port: 50211

matchingServiceAdapter:
  entityId: http://www.test-rp-ms.gov.uk/SAML2/MD
  externalUrl: http://localhost:${MSA_PORT:-50210}/matching-service/POST

localMatchingService:
  matchUrl: ${LMS_MATCH_URL:-http://todo/lms/match/url}
  accountCreationUrl: ${LMS_UAC_URL:-http://todo/lms/account-creation/url}

hub:
  ssoUrl: ${VERIFY_SSO_URL:-https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/SAML2/SSO}
  trustStore:
    type: file
    store: ${HUB_TRUST_STORE_PATH}
    password: puppet

metadata:
  url: ${METADATA_URL:-https://compliance-tool-reference.ida.digital.cabinet-office.gov.uk/SAML2/metadata/federation}
  jerseyClientName: metadata-client
  trustStore:
    type: file
    store: ${METADATA_TRUST_STORE_PATH}
    password: puppet

signingKeys:
  primary:
    publicKey:
      type: encoded
      cert: ${MSA_SIGNING_CERT_PRIMARY:-encoded-cert}
      name: signing.primary.crt
    privateKey:
      type: encoded
      key: ${MSA_SIGNING_KEY_PRIMARY:-encoded-key}

encryptionKeys:
  - publicKey:
      type: encoded
      cert: ${MSA_ENCRYPTION_CERT_PRIMARY:-encoded-cert}
      name: encryption.primary.crt
    privateKey:
      type: encoded
      key: ${MSA_ENCRYPTION_KEY_PRIMARY:-encoded-key}
